package com.repforth.core.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A saved plan (§7).
 *
 * [source] records how it came to exist — built by hand, generated by the rules
 * engine, or produced from an AI request. That is not decoration: §8 requires a
 * generated plan to be an editable set of workout cards rather than a chat
 * transcript, and the moment a user edits a generated plan it stops being
 * faithful to what was generated. Keeping the origin lets the app say where a
 * plan came from without implying its current contents are still that.
 */
@Entity(
    tableName = "workout_template",
    foreignKeys = [
        ForeignKey(
            entity = TrainingWeekEntity::class,
            parentColumns = ["id"],
            childColumns = ["week_id"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("week_id")],
)
data class WorkoutTemplateEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "notes")
    val notes: String?,

    /** `MANUAL`, `RULES` or `AI`. */
    @ColumnInfo(name = "source")
    val source: String,

    /** Null for a standalone workout; references [TrainingWeekEntity.id] when part of a week. */
    @ColumnInfo(name = "week_id")
    val weekId: String? = null,

    /** Zero-based position of this day within its week, or null when standalone. */
    @ColumnInfo(name = "week_position")
    val weekPosition: Int? = null,

    /** 1..7 (ISO Monday = 1), or null when unassigned or standalone. */
    @ColumnInfo(name = "day_of_week")
    val dayOfWeek: Int? = null,

    @ColumnInfo(name = "created_at")
    val createdAt: Long,

    @ColumnInfo(name = "updated_at")
    val updatedAt: Long,
)

/**
 * One exercise in a plan, with its targets.
 *
 * Reps and duration are both nullable and exactly one is expected: a plank has a
 * duration and no reps, a curl has reps and no duration. Modelling that as two
 * nullable columns rather than a units discriminator keeps the queries simple,
 * and the invariant is enforced where the row is written.
 *
 * [exerciseId] is a catalog id with no foreign key — see the note in
 * ProfileEntity.kt for why user data never cascades from the catalog.
 */
@Entity(
    tableName = "template_exercise",
    foreignKeys = [
        ForeignKey(
            entity = WorkoutTemplateEntity::class,
            parentColumns = ["id"],
            childColumns = ["template_id"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("template_id"), Index("exercise_id")],
)
data class TemplateExerciseEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String,

    @ColumnInfo(name = "template_id")
    val templateId: String,

    @ColumnInfo(name = "exercise_id")
    val exerciseId: String,

    /** Display order. Zero-based and contiguous within a template. */
    @ColumnInfo(name = "position")
    val position: Int,

    @ColumnInfo(name = "target_sets")
    val targetSets: Int,

    @ColumnInfo(name = "target_reps")
    val targetReps: Int?,

    @ColumnInfo(name = "target_duration_ms")
    val targetDurationMs: Long?,

    /** Kilograms, always. Null when the exercise is bodyweight or untracked. */
    @ColumnInfo(name = "target_weight_kg")
    val targetWeightKg: Double?,

    @ColumnInfo(name = "rest_ms")
    val restMs: Long,

    @ColumnInfo(name = "created_at")
    val createdAt: Long,

    @ColumnInfo(name = "updated_at")
    val updatedAt: Long,
)
