package com.repforth.wear

import android.Manifest
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import androidx.wear.ongoing.OngoingActivity
import androidx.wear.ongoing.Status
import com.repforth.core.wearprotocol.WearPhase
import com.repforth.core.wearprotocol.WearWorkoutState
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * §3's "ongoing activity entry so the user can return from the watch face".
 *
 * A watch spends a workout on its face, not in an app — that is the whole point
 * of a remote you glance at. Before this there was no way back except the app
 * launcher, which on a wrist is a scroll through every installed app while
 * holding a plank.
 *
 * An [OngoingActivity] is a decoration on an ordinary ongoing notification: the
 * notification is what exists, and the decoration is what promotes it to a chip
 * on the watch face with a touch target that reopens the app. So there is one
 * object to keep correct, not two.
 *
 * **It is driven from the store rather than from the listener service.** The
 * snapshot reaches the watch two ways — pushed by the Data Layer while nothing
 * is on screen, and pulled by [WearWorkoutStore.refresh] when the app opens cold
 * — and a chip posted on only one of those paths is a chip that is missing
 * exactly when the app was not running, which is the case it exists for.
 *
 * Silent and low-importance on purpose. This is a way back, not an alert; §3's
 * alert is the haptic in [WearHaptics], which is a separate moment with a
 * separate switch.
 */
@Singleton
class WearWorkoutNotification @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val manager = NotificationManagerCompat.from(context)

    /**
     * Show, update or remove the chip to match [state].
     *
     * Null and the two terminal phases all mean "no workout is running", and all
     * three remove it. A chip left behind after a workout is worse than none: it
     * offers a way back into a session that no longer exists.
     */
    fun update(state: WearWorkoutState?) {
        if (state == null || state.phase == WearPhase.Finished || state.phase == WearPhase.Abandoned) {
            manager.cancel(NOTIFICATION_ID)
            return
        }

        // Two questions, not one, and they are asked inline rather than behind a
        // helper because lint only recognises the permission check in the method
        // that notifies.
        //
        // The runtime grant exists from Android 13; below that a user can still
        // switch notifications off in settings. Either answer means the same
        // thing here, and neither is an error: `notify` without the permission
        // does not throw, it silently does nothing, so the log is the only thing
        // that will later separate "the user said no" from "this is broken".
        val granted = Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
            ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) ==
            PackageManager.PERMISSION_GRANTED
        if (!granted || !manager.areNotificationsEnabled()) {
            Log.i(TAG, "Not showing the ongoing activity: notifications are off")
            return
        }

        createChannel()
        manager.notify(NOTIFICATION_ID, build(state))
    }

    private fun build(state: WearWorkoutState): Notification {
        val touch = PendingIntent.getActivity(
            context,
            0,
            Intent(context, WearMainActivity::class.java)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP),
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT,
        )

        val builder = NotificationCompat.Builder(context, CHANNEL_ID)
            // A notification's small icon is drawn as a silhouette -- the system
            // keeps the alpha and throws the colour away -- so this is the
            // single-path dumbbell rather than the launcher icon, which would
            // arrive as a blob. Generated by the same script as the phone's copy
            // and byte-identical to it; see tools/icons-wear.txt.
            .setSmallIcon(R.drawable.rf_sym_fitness_center)
            .setContentTitle(state.exerciseName)
            .setContentText(
                context.getString(R.string.wear_set_of, state.setNumber, state.totalSets),
            )
            .setOngoing(true)
            .setSilent(true)
            .setCategory(NotificationCompat.CATEGORY_WORKOUT)
            .setContentIntent(touch)

        OngoingActivity.Builder(context, NOTIFICATION_ID, builder)
            .setStaticIcon(R.drawable.rf_sym_fitness_center)
            .setTouchIntent(touch)
            // What the watch face itself shows on the chip. The exercise name is
            // the one thing worth the room: which set you are on is already the
            // first thing the app draws when the chip is tapped.
            .setStatus(Status.forPart(Status.TextPart(state.exerciseName)))
            .build()
            .apply(context)

        return builder.build()
    }

    private fun createChannel() {
        val channel = NotificationChannel(
            CHANNEL_ID,
            context.getString(R.string.wear_channel_workout),
            // Low, and silent above. The phone already buzzes and beeps for the
            // moments that deserve it, and this watch buzzes for the two §3 names
            // -- a chip that also rang would be a third opinion about the same
            // set.
            NotificationManager.IMPORTANCE_LOW,
        )
        manager.createNotificationChannel(channel)
    }

    private companion object {
        const val TAG = "WearWorkoutNotification"
        const val CHANNEL_ID = "workout"

        /**
         * One id, reused.
         *
         * Updating a running workout must replace the chip rather than stack a
         * second one beside it, and ending it must be able to remove exactly the
         * one that is there.
         */
        const val NOTIFICATION_ID = 1
    }
}
