package com.repforth.core.exercisedata

import androidx.annotation.StringRes
import com.repforth.core.model.BodyPart
import com.repforth.core.model.Equipment
import com.repforth.core.model.Muscle

/*
 * GENERATED by tools/generate-term-labels.py. Do not edit.
 *
 * The enums carry upstream slugs, which are English and lower case and belong in
 * storage, not on screen. These map each constant to a translated display name.
 * Both locales are checked to declare the same keys before this file is written.
 */

/**
 * The localised display name for this bodyPart.
 *
 * Exhaustive, so adding a constant without a label fails to compile.
 */
val BodyPart.labelRes: Int
    @StringRes get() = when (this) {
    BodyPart.BACK -> R.string.body_part_back
    BodyPart.CARDIO -> R.string.body_part_cardio
    BodyPart.CHEST -> R.string.body_part_chest
    BodyPart.LOWER_ARMS -> R.string.body_part_lower_arms
    BodyPart.LOWER_LEGS -> R.string.body_part_lower_legs
    BodyPart.NECK -> R.string.body_part_neck
    BodyPart.SHOULDERS -> R.string.body_part_shoulders
    BodyPart.UPPER_ARMS -> R.string.body_part_upper_arms
    BodyPart.UPPER_LEGS -> R.string.body_part_upper_legs
    BodyPart.WAIST -> R.string.body_part_waist
    }


/**
 * The localised display name for this equipment.
 *
 * Exhaustive, so adding a constant without a label fails to compile.
 */
val Equipment.labelRes: Int
    @StringRes get() = when (this) {
    Equipment.ASSISTED -> R.string.equipment_assisted
    Equipment.BAND -> R.string.equipment_band
    Equipment.BARBELL -> R.string.equipment_barbell
    Equipment.BODY_WEIGHT -> R.string.equipment_body_weight
    Equipment.BOSU_BALL -> R.string.equipment_bosu_ball
    Equipment.CABLE -> R.string.equipment_cable
    Equipment.DUMBBELL -> R.string.equipment_dumbbell
    Equipment.ELLIPTICAL_MACHINE -> R.string.equipment_elliptical_machine
    Equipment.EZ_BARBELL -> R.string.equipment_ez_barbell
    Equipment.HAMMER -> R.string.equipment_hammer
    Equipment.KETTLEBELL -> R.string.equipment_kettlebell
    Equipment.LEVERAGE_MACHINE -> R.string.equipment_leverage_machine
    Equipment.MEDICINE_BALL -> R.string.equipment_medicine_ball
    Equipment.OLYMPIC_BARBELL -> R.string.equipment_olympic_barbell
    Equipment.RESISTANCE_BAND -> R.string.equipment_resistance_band
    Equipment.ROLLER -> R.string.equipment_roller
    Equipment.ROPE -> R.string.equipment_rope
    Equipment.SKIERG_MACHINE -> R.string.equipment_skierg_machine
    Equipment.SLED_MACHINE -> R.string.equipment_sled_machine
    Equipment.SMITH_MACHINE -> R.string.equipment_smith_machine
    Equipment.STABILITY_BALL -> R.string.equipment_stability_ball
    Equipment.STATIONARY_BIKE -> R.string.equipment_stationary_bike
    Equipment.STEPMILL_MACHINE -> R.string.equipment_stepmill_machine
    Equipment.TIRE -> R.string.equipment_tire
    Equipment.TRAP_BAR -> R.string.equipment_trap_bar
    Equipment.UPPER_BODY_ERGOMETER -> R.string.equipment_upper_body_ergometer
    Equipment.WEIGHTED -> R.string.equipment_weighted
    Equipment.WHEEL_ROLLER -> R.string.equipment_wheel_roller
    }

/**
 * A one-line explanation of what this piece of kit actually is.
 *
 * Gym equipment is not common knowledge. Onboarding asks people to name what
 * they can train with, and that answer decides what they are programmed for
 * months — so the obscure two thirds of the list need to say what they are
 * rather than assume it. An icon would not help here: most of this kit has no
 * recognisable glyph, and a line drawing of a trap bar does not teach anyone
 * what a trap bar is.
 *
 * Exhaustive, so adding a constant without an explanation fails to compile.
 */
val Equipment.detailRes: Int
    @StringRes get() = when (this) {
    Equipment.ASSISTED -> R.string.equipment_assisted_detail
    Equipment.BAND -> R.string.equipment_band_detail
    Equipment.BARBELL -> R.string.equipment_barbell_detail
    Equipment.BODY_WEIGHT -> R.string.equipment_body_weight_detail
    Equipment.BOSU_BALL -> R.string.equipment_bosu_ball_detail
    Equipment.CABLE -> R.string.equipment_cable_detail
    Equipment.DUMBBELL -> R.string.equipment_dumbbell_detail
    Equipment.ELLIPTICAL_MACHINE -> R.string.equipment_elliptical_machine_detail
    Equipment.EZ_BARBELL -> R.string.equipment_ez_barbell_detail
    Equipment.HAMMER -> R.string.equipment_hammer_detail
    Equipment.KETTLEBELL -> R.string.equipment_kettlebell_detail
    Equipment.LEVERAGE_MACHINE -> R.string.equipment_leverage_machine_detail
    Equipment.MEDICINE_BALL -> R.string.equipment_medicine_ball_detail
    Equipment.OLYMPIC_BARBELL -> R.string.equipment_olympic_barbell_detail
    Equipment.RESISTANCE_BAND -> R.string.equipment_resistance_band_detail
    Equipment.ROLLER -> R.string.equipment_roller_detail
    Equipment.ROPE -> R.string.equipment_rope_detail
    Equipment.SKIERG_MACHINE -> R.string.equipment_skierg_machine_detail
    Equipment.SLED_MACHINE -> R.string.equipment_sled_machine_detail
    Equipment.SMITH_MACHINE -> R.string.equipment_smith_machine_detail
    Equipment.STABILITY_BALL -> R.string.equipment_stability_ball_detail
    Equipment.STATIONARY_BIKE -> R.string.equipment_stationary_bike_detail
    Equipment.STEPMILL_MACHINE -> R.string.equipment_stepmill_machine_detail
    Equipment.TIRE -> R.string.equipment_tire_detail
    Equipment.TRAP_BAR -> R.string.equipment_trap_bar_detail
    Equipment.UPPER_BODY_ERGOMETER -> R.string.equipment_upper_body_ergometer_detail
    Equipment.WEIGHTED -> R.string.equipment_weighted_detail
    Equipment.WHEEL_ROLLER -> R.string.equipment_wheel_roller_detail
    }


/**
 * The localised display name for this muscle.
 *
 * Exhaustive, so adding a constant without a label fails to compile.
 */
val Muscle.labelRes: Int
    @StringRes get() = when (this) {
    Muscle.ABDOMINALS -> R.string.muscle_abdominals
    Muscle.ABDUCTORS -> R.string.muscle_abductors
    Muscle.ABS -> R.string.muscle_abs
    Muscle.ADDUCTORS -> R.string.muscle_adductors
    Muscle.ANKLE_STABILIZERS -> R.string.muscle_ankle_stabilizers
    Muscle.ANKLES -> R.string.muscle_ankles
    Muscle.BACK -> R.string.muscle_back
    Muscle.BICEPS -> R.string.muscle_biceps
    Muscle.BRACHIALIS -> R.string.muscle_brachialis
    Muscle.CALVES -> R.string.muscle_calves
    Muscle.CARDIOVASCULAR_SYSTEM -> R.string.muscle_cardiovascular_system
    Muscle.CHEST -> R.string.muscle_chest
    Muscle.CORE -> R.string.muscle_core
    Muscle.DELTOIDS -> R.string.muscle_deltoids
    Muscle.DELTS -> R.string.muscle_delts
    Muscle.FEET -> R.string.muscle_feet
    Muscle.FOREARMS -> R.string.muscle_forearms
    Muscle.GLUTES -> R.string.muscle_glutes
    Muscle.GRIP_MUSCLES -> R.string.muscle_grip_muscles
    Muscle.GROIN -> R.string.muscle_groin
    Muscle.HAMSTRINGS -> R.string.muscle_hamstrings
    Muscle.HANDS -> R.string.muscle_hands
    Muscle.HIP_FLEXORS -> R.string.muscle_hip_flexors
    Muscle.INNER_THIGHS -> R.string.muscle_inner_thighs
    Muscle.LATISSIMUS_DORSI -> R.string.muscle_latissimus_dorsi
    Muscle.LATS -> R.string.muscle_lats
    Muscle.LEVATOR_SCAPULAE -> R.string.muscle_levator_scapulae
    Muscle.LOWER_ABS -> R.string.muscle_lower_abs
    Muscle.LOWER_BACK -> R.string.muscle_lower_back
    Muscle.OBLIQUES -> R.string.muscle_obliques
    Muscle.PECTORALS -> R.string.muscle_pectorals
    Muscle.QUADRICEPS -> R.string.muscle_quadriceps
    Muscle.QUADS -> R.string.muscle_quads
    Muscle.REAR_DELTOIDS -> R.string.muscle_rear_deltoids
    Muscle.RHOMBOIDS -> R.string.muscle_rhomboids
    Muscle.ROTATOR_CUFF -> R.string.muscle_rotator_cuff
    Muscle.SERRATUS_ANTERIOR -> R.string.muscle_serratus_anterior
    Muscle.SHINS -> R.string.muscle_shins
    Muscle.SHOULDERS -> R.string.muscle_shoulders
    Muscle.SOLEUS -> R.string.muscle_soleus
    Muscle.SPINE -> R.string.muscle_spine
    Muscle.STERNOCLEIDOMASTOID -> R.string.muscle_sternocleidomastoid
    Muscle.TRAPEZIUS -> R.string.muscle_trapezius
    Muscle.TRAPS -> R.string.muscle_traps
    Muscle.TRICEPS -> R.string.muscle_triceps
    Muscle.UPPER_BACK -> R.string.muscle_upper_back
    Muscle.UPPER_CHEST -> R.string.muscle_upper_chest
    Muscle.WRIST_EXTENSORS -> R.string.muscle_wrist_extensors
    Muscle.WRIST_FLEXORS -> R.string.muscle_wrist_flexors
    Muscle.WRISTS -> R.string.muscle_wrists
    }
