package com.repforth.core.media.manifest

import kotlinx.serialization.Serializable

/**
 * Manifest format generated by `tools/import-dataset.py` from `dataset-version.toml` (§6, §9).
 *
 * Immutable by construction: every entry maps an exercise ID to its exact
 * relative paths, expected SHA-256 hashes, and byte sizes for both the thumbnail
 * and the animated demonstration.
 */
@Serializable
data class MediaManifest(
    val commit: String,
    val mediaVersion: Int,
    val baseUrl: String,
    val attribution: String,
    val entries: List<MediaManifestEntry>,
)

@Serializable
data class MediaManifestEntry(
    val id: String,
    val thumbnail: MediaManifestAsset,
    val animation: MediaManifestAsset,
)

@Serializable
data class MediaManifestAsset(
    val path: String,
    val sha256: String,
    val bytes: Long,
)
