package com.repforth.core.secrets

import android.content.Context
import com.google.crypto.tink.Aead
import com.google.crypto.tink.KeyTemplates
import com.google.crypto.tink.aead.AeadConfig
import com.google.crypto.tink.integration.android.AndroidKeysetManager
import java.io.File
import java.security.GeneralSecurityException
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext

/**
 * Provider secrets, encrypted under a non-exportable Android Keystore key (§8).
 *
 * The shape §8 asks for, in three parts:
 *
 * 1. A data-encryption keyset generated by Tink and kept in shared preferences,
 *    itself encrypted by a master key that lives in the Android Keystore and
 *    cannot be exported off the device.
 * 2. The user's secret encrypted with that keyset's AEAD.
 * 3. Only the resulting ciphertext written to internal storage.
 *
 * **Ciphertext goes in a file, not DataStore or Room.** §20 requires keys to be
 * absent from both, and "it is only the encrypted form" is exactly the argument
 * that erodes a rule like that. A file under `filesDir` keeps the answer to
 * "is a key in the database?" a flat no.
 *
 * **The id is the associated data.** AEAD binds ciphertext to it, so a file
 * copied from one slot to another fails to decrypt rather than silently
 * resolving as a different provider's key. It costs one argument and closes a
 * whole class of confusion.
 *
 * **Nothing here is excluded from backup, because nothing is backed up.**
 * `android:allowBackup` is false and `BackupPolicyTest` holds it, which covers
 * §8's fourth point for the whole app rather than for this directory alone.
 *
 * What this does not claim: a determined attacker with a rooted device and the
 * app's uid can still get at a secret the app itself can decrypt. §8 says as
 * much. The goal is platform-appropriate protection, not an impossible one.
 */
internal class KeystoreSecretStore(
    private val context: Context,
    private val io: CoroutineDispatcher,
) : SecretStore {

    /**
     * Tink registration and keyset generation both touch disk and the Keystore,
     * and generating a master key twice concurrently is how two callers end up
     * with keysets that cannot read each other's ciphertext. One lock, resolved
     * once.
     */
    private val lock = Mutex()
    private var cached: Aead? = null

    private suspend fun aead(): Aead = lock.withLock {
        cached ?: withContext(io) {
            AeadConfig.register()
            AndroidKeysetManager.Builder()
                .withSharedPref(context, KEYSET_NAME, PREFERENCE_FILE)
                .withKeyTemplate(KeyTemplates.get("AES256_GCM"))
                .withMasterKeyUri(MASTER_KEY_URI)
                .build()
                .keysetHandle
                .getPrimitive(Aead::class.java)
                .also { cached = it }
        }
    }

    override suspend fun put(id: SecretId, secret: String) = withContext(io) {
        val ciphertext = aead().encrypt(secret.toByteArray(Charsets.UTF_8), id.aad())
        val file = fileFor(id)
        file.parentFile?.mkdirs()
        file.writeBytes(ciphertext)
    }

    /**
     * Returns null rather than throwing when the ciphertext will not decrypt.
     *
     * That happens for real and recoverable reasons — the Keystore key is
     * dropped when the device's lock screen credentials are removed, and a
     * restore onto different hardware cannot bring it back. The honest response
     * is "there is no usable key here", which sends the user to re-enter one,
     * rather than an exception on every screen that asks.
     */
    override suspend fun get(id: SecretId): String? = withContext(io) {
        val file = fileFor(id)
        if (!file.exists()) return@withContext null
        try {
            aead().decrypt(file.readBytes(), id.aad()).toString(Charsets.UTF_8)
        } catch (e: GeneralSecurityException) {
            null
        }
    }

    override suspend fun contains(id: SecretId): Boolean = withContext(io) {
        fileFor(id).exists()
    }

    override suspend fun delete(id: SecretId) = withContext(io) {
        fileFor(id).delete()
        Unit
    }

    override suspend fun clear() = withContext(io) {
        directory().deleteRecursively()
        Unit
    }

    private fun directory() = File(context.filesDir, DIRECTORY)

    /**
     * Ids are hex-encoded into the filename.
     *
     * An id is not secret, but it is caller-supplied, and a caller-supplied
     * string interpolated into a path is a directory traversal. Encoding
     * removes the question rather than validating it away.
     */
    private fun fileFor(id: SecretId) = File(
        directory(),
        id.value.toByteArray(Charsets.UTF_8).joinToString("") { "%02x".format(it) },
    )

    private fun SecretId.aad(): ByteArray = value.toByteArray(Charsets.UTF_8)

    private companion object {
        const val DIRECTORY = "secrets"
        const val KEYSET_NAME = "repforth_secrets_keyset"
        const val PREFERENCE_FILE = "repforth_secrets"
        const val MASTER_KEY_URI = "android-keystore://repforth_secrets_master_key"
    }
}
