"""Maps the categorical enums to their display-name string resources.

Generated rather than hand-written because there are 88 of them and a typo would
be a wrong label rather than a compile error -- `R.string` constants are Ints, so
nothing would notice `Muscle.LATS` pointing at the traps.

A `when` over the enum rather than a lookup by name: Kotlin's exhaustiveness
check then makes a missing entry a compile failure, and no resource id is
resolved by string at runtime, which `getIdentifier` would have done and R8 would
have stripped.

Run after tools/extract-vocabulary.py, and after regenerating exercise_terms.xml.

Usage: python tools/generate-term-labels.py
"""
import io
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VOCABULARY = os.path.join(ROOT, "core/model/src/test/resources/dataset-vocabulary.json")
TERMS_EN = os.path.join(ROOT, "core/exercise-data/src/main/res/values/exercise_terms.xml")
TERMS_TR = os.path.join(ROOT, "core/exercise-data/src/main/res/values-tr/exercise_terms.xml")
OUT = os.path.join(
    ROOT,
    "core/exercise-data/src/main/java/com/repforth/core/exercisedata/CatalogTerms.kt",
)

FIELDS = (
    ("BodyPart", "bodyPart", "body_part"),
    ("Equipment", "equipment", "equipment"),
    ("Muscle", "muscle", "muscle"),
)


def slug_key(prefix, value):
    return "%s_%s" % (prefix, re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_"))


def constant(value):
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def declared(path):
    return {e.get("name") for e in ET.parse(path).getroot().findall("string")}


def main():
    vocabulary = json.load(io.open(VOCABULARY, encoding="utf-8"))
    english, turkish = declared(TERMS_EN), declared(TERMS_TR)

    # §13 in miniature: a term with only one translation would render blank in
    # the other locale, so refuse to generate rather than ship that.
    only_en, only_tr = sorted(english - turkish), sorted(turkish - english)
    if only_en or only_tr:
        sys.exit(
            "generate-term-labels: exercise_terms.xml files disagree\n"
            "  only in values/   : %s\n  only in values-tr/: %s" % (only_en, only_tr)
        )

    blocks = []
    for kotlin_type, field, prefix in FIELDS:
        lines = []
        for value in vocabulary[field]:
            key = slug_key(prefix, value)
            if key not in english:
                sys.exit(
                    "generate-term-labels: no string '%s' for %s '%s'. "
                    "Regenerate exercise_terms.xml." % (key, kotlin_type, value)
                )
            lines.append("    %s.%s -> R.string.%s" % (kotlin_type, constant(value), key))
        blocks.append(TEMPLATE_BLOCK % {
            "type": kotlin_type,
            "lower": kotlin_type[0].lower() + kotlin_type[1:],
            "cases": "\n".join(lines),
        })

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(TEMPLATE % "\n".join(blocks))
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    for kotlin_type, field, _ in FIELDS:
        print("  %-10s %d labels" % (kotlin_type, len(vocabulary[field])))


TEMPLATE_BLOCK = '''
/**
 * The localised display name for this %(lower)s.
 *
 * Exhaustive, so adding a constant without a label fails to compile.
 */
val %(type)s.labelRes: Int
    @StringRes get() = when (this) {
%(cases)s
    }
'''

TEMPLATE = '''package com.repforth.core.exercisedata

import androidx.annotation.StringRes
import com.repforth.core.model.BodyPart
import com.repforth.core.model.Equipment
import com.repforth.core.model.Muscle

/*
 * GENERATED by tools/generate-term-labels.py. Do not edit.
 *
 * The enums carry upstream slugs, which are English and lower case and belong in
 * storage, not on screen. These map each constant to a translated display name.
 * Both locales are checked to declare the same keys before this file is written.
 */
%s'''


if __name__ == "__main__":
    main()
