"""Turns raw device screenshots into the README's gallery.

    python tools/readme-shots.py <folder of 1080x2400 PNGs>

Writes docs/screenshots/*.png. Only the processed images are committed; the raw
captures are not.

## Why device captures and not the screenshot goldens

The goldens render every exercise with `MediaRef.Unavailable`, so they draw the
app's placeholder icon where the exercise animation belongs. That is most of
what the session and catalog screens are, and a gallery that omits it is selling
a different app. **The owner asked for the animations, knowing what it costs.**

What it costs is worth writing down rather than discovering later:

- **The imagery is Gym visual's** and is not ours to redistribute (NOTICE.md).
  A screenshot for documentation is a far easier case than shipping the asset,
  and the app credits the source on screen wherever it draws one -- but these
  images do put third-party artwork in a public repository, deliberately.
- **They are captures of a real phone**, so what is in them is real training
  data. The status bar is cropped off for that reason among others: it carried
  notification icons.
- **They go stale silently.** The goldens were regenerated by the test suite
  whenever the UI moved. These are not. Retake them when a screen changes.

## What it does to them

Crops the status bar and the gesture bar, rounds the corners so a tile reads as
a device rather than a crop, and halves the resolution -- 1080px wide is four
times what GitHub draws in a four-column table.

Tiles keep their own heights. Padding them to a common height was tried on the
golden version of this script and was worse: it put dead space straight back
into the shortest screens, which is what the trim existed to remove.
"""
import os
import sys

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("readme-shots: needs pillow (pip install pillow)")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "docs", "screenshots")

# Raw capture -> published name, in the order they appear in the README.
SHOTS = [
    ("session-active.png", "training.png"),
    ("session-rest.png", "rest.png"),
    ("session-progression.png", "progression.png"),
    ("progress.png", "progress.png"),
    ("detail.png", "exercise.png"),
    ("catalog.png", "catalog.png"),
]

# Measured on the capture rather than guessed: the status bar ends and the app's
# background begins at 100, and the gesture bar takes the last 40.
STATUS_BAR = 100
GESTURE_BAR = 40

WIDTH = 540
CORNER_RADIUS = 28


def rounded(image, radius):
    """Rounds the corners, so a tile reads as a device rather than a crop."""
    mask = Image.new("L", image.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, image.width - 1, image.height - 1), radius=radius, fill=255
    )
    out = Image.new("RGBA", image.size, (0, 0, 0, 0))
    out.paste(image, (0, 0), mask)
    return out


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: python tools/readme-shots.py <folder of raw captures>")
    raw_dir = sys.argv[1]
    os.makedirs(OUT_DIR, exist_ok=True)

    for source, name in SHOTS:
        full = os.path.join(raw_dir, source)
        if not os.path.isfile(full):
            sys.exit("readme-shots: no capture at %s" % full)
        image = Image.open(full).convert("RGB")
        cropped = image.crop((0, STATUS_BAR, image.width, image.height - GESTURE_BAR))
        scale = WIDTH / cropped.width
        resized = cropped.resize((WIDTH, round(cropped.height * scale)), Image.LANCZOS)
        rounded(resized, CORNER_RADIUS).save(os.path.join(OUT_DIR, name), optimize=True)
        print("docs/screenshots/%s  %dx%d" % (name, resized.width, resized.height))


if __name__ == "__main__":
    main()
