"""Turns the body-map SVGs into a Kotlin source file of path data.

Why not ship the SVGs as vector drawables? Because the picker needs to tint each
region independently and to know which region a tap landed in. Both want the
geometry as data, not as a pre-rendered asset -- so the path strings become
Kotlin constants that Compose parses into Path objects once.

The conversion is deliberately dumb: it copies `d` attributes verbatim. Android's
PathParser accepts the same grammar as SVG, so anything clever here would only be
a chance to corrupt the artwork. It validates instead, and refuses to write a
file whose ids do not match the BodyRegion model.

Usage: python tools/svg-to-bodymap.py
"""
import io
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "art/bodymap")
OUT = os.path.join(
    ROOT,
    "core/designsystem/src/main/java/com/repforth/core/designsystem/component/BodyMapArt.kt",
)
MODEL = os.path.join(ROOT, "core/model/src/main/java/com/repforth/core/model/BodyRegion.kt")
SVG_NS = "{http://www.w3.org/2000/svg}"


def regions_for_view(view):
    """Reads the expected id list out of BodyRegion.kt, so the model stays the
    source of truth and this script cannot invent a region the app has no
    constant for."""
    text = io.open(MODEL, encoding="utf-8").read()
    body = text[text.index("enum class BodyRegion"):text.index("\n    ;")]
    found = []
    for name, views in re.findall(r"^    ([A-Z_]+)\(setOf\(([^)]*)\)\),", body, re.M):
        if "BodyView." + view in views:
            found.append(name.lower().replace("_", "-"))
    return found


def parse(path):
    if not os.path.exists(path):
        sys.exit("svg-to-bodymap: missing %s -- has the artwork been generated?" % path)
    tree = ET.parse(path)
    root = tree.getroot()
    view_box = root.get("viewBox")
    if not view_box:
        sys.exit("svg-to-bodymap: %s has no viewBox" % path)

    paths = {}
    order = []
    for el in root.iter(SVG_NS + "path"):
        ident = el.get("id")
        d = el.get("d")
        if not ident or not d:
            continue
        if ident in paths:
            sys.exit("svg-to-bodymap: duplicate id '%s' in %s" % (ident, path))
        paths[ident] = " ".join(d.split())
        order.append(ident)
    return view_box, paths, order


def check(name, paths, expected):
    got = set(paths) - {"silhouette"}
    want = set(expected)
    if "silhouette" not in paths:
        sys.exit("svg-to-bodymap: %s has no path with id 'silhouette'" % name)
    missing, extra = sorted(want - got), sorted(got - want)
    if missing or extra:
        sys.exit(
            "svg-to-bodymap: %s ids do not match BodyRegion\n  missing: %s\n  extra:   %s"
            % (name, missing or "none", extra or "none")
        )


def kotlin_map(paths, expected):
    lines = []
    for ident in expected:
        lines.append('        "%s" to\n            "%s",' % (ident, paths[ident]))
    return "\n".join(lines)


def main():
    front_box, front, _ = parse(os.path.join(ART, "body-front.svg"))
    back_box, back, _ = parse(os.path.join(ART, "body-back.svg"))

    if front_box != back_box:
        sys.exit(
            "svg-to-bodymap: the two views must share a viewBox so they align "
            "when cross-faded (front %r, back %r)" % (front_box, back_box)
        )

    expected_front = regions_for_view("FRONT")
    expected_back = regions_for_view("BACK")
    check("body-front.svg", front, expected_front)
    check("body-back.svg", back, expected_back)

    width, height = view_box_size(front_box)

    source = TEMPLATE % {
        "width": width,
        "height": height,
        "front_silhouette": front["silhouette"],
        "back_silhouette": back["silhouette"],
        "front": kotlin_map(front, expected_front),
        "back": kotlin_map(back, expected_back),
    }
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(source)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  viewBox %s  front %d regions  back %d regions"
          % (front_box, len(expected_front), len(expected_back)))


def view_box_size(view_box):
    parts = [float(p) for p in view_box.replace(",", " ").split()]
    if len(parts) != 4 or parts[0] != 0 or parts[1] != 0:
        sys.exit("svg-to-bodymap: expected a viewBox starting at 0 0, got %r" % view_box)
    return parts[2], parts[3]


TEMPLATE = '''package com.repforth.core.designsystem.component

/*
 * GENERATED by tools/svg-to-bodymap.py from the SVGs in art/bodymap.
 * Do not edit. (Kotlin block comments nest, so no path here may contain a
 * slash-star: it would open a comment that never closes.)
 *
 * Path data rather than a drawable resource: the picker tints each region
 * independently and has to know which region a tap landed in, and both need the
 * geometry as data. The strings use SVG path grammar, which Compose's PathParser
 * accepts unchanged.
 */

/** The coordinate space every path below is expressed in. Both views share it. */
object BodyMapViewport {
    const val WIDTH = %(width)ff
    const val HEIGHT = %(height)ff
}

/** The body outline, drawn under the regions. */
object BodyMapSilhouette {
    const val FRONT = "%(front_silhouette)s"
    const val BACK = "%(back_silhouette)s"
}

/**
 * Region paths, keyed by [com.repforth.core.model.BodyRegion.svgId].
 *
 * A missing key is a build error waiting to happen rather than a crash: the
 * generator refuses to write this file unless the ids match the model exactly.
 */
object BodyMapRegions {
    val FRONT: Map<String, String> = mapOf(
%(front)s
    )

    val BACK: Map<String, String> = mapOf(
%(back)s
    )
}
'''


if __name__ == "__main__":
    main()
