"""Convert Material Symbols SVGs into Android vector drawables.

Material Symbols ship on a 960x960 grid whose origin is at the *bottom* left:
the viewBox is `0 -960 960 960`. Android's vector drawable has no negative
viewport origin, so the path is wrapped in a group translated down by 960, which
puts the same coordinates back on screen. Getting this wrong does not fail --
the icon simply draws off-canvas and every icon in the app is blank, which is
why the offset is asserted rather than assumed.

No tint is baked in. Compose's `Icon` tints the painter it is given, so a tint
here would be either redundant or fighting it -- and a theme attribute in a
library drawable is the same trap that made the first hand-authored icons crash
on a platform theme.

Usage: python svg-to-vector.py <svg-dir> <out-dir>
"""

import os
import re
import sys

VIEWBOX = re.compile(r'viewBox="([-\d.]+) ([-\d.]+) ([-\d.]+) ([-\d.]+)"')
PATH = re.compile(r'<path[^>]*\bd="([^"]+)"')

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!--
    {name} - Material Symbols {style}, Apache 2.0.
    Generated by tools/fetch-icons.sh. Do not edit; rerun the script.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="{vw:g}"
    android:viewportHeight="{vh:g}">
    <group android:translateY="{ty:g}">
{paths}
    </group>
</vector>
"""

PATH_LINE = '        <path\n            android:fillColor="#FF000000"\n            android:pathData="{d}" />'


def convert(svg_text, name, style):
    box = VIEWBOX.search(svg_text)
    if not box:
        raise ValueError("%s: no viewBox" % name)
    min_x, min_y, width, height = (float(v) for v in box.groups())

    if min_x != 0.0:
        raise ValueError("%s: unexpected viewBox origin x=%s" % (name, min_x))

    paths = PATH.findall(svg_text)
    if not paths:
        raise ValueError("%s: no path data" % name)

    return TEMPLATE.format(
        name=name,
        style=style,
        vw=width,
        vh=height,
        # min_y is -960 for these, so the shift is +960.
        ty=-min_y,
        paths="\n".join(PATH_LINE.format(d=d) for d in paths),
    )


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2

    svg_dir, out_dir = sys.argv[1], sys.argv[2]
    style = os.environ.get("ICON_STYLE", "materialsymbolsrounded")
    written = 0

    for filename in sorted(os.listdir(svg_dir)):
        if not filename.endswith(".svg"):
            continue
        name = filename[: -len(".svg")]
        with open(os.path.join(svg_dir, filename), encoding="utf-8") as handle:
            svg = handle.read()

        xml = convert(svg, name, style)
        target = os.path.join(out_dir, "rf_sym_%s.xml" % name)
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(xml)
        written += 1

    print("svg-to-vector: wrote %d drawables" % written)
    return 0


if __name__ == "__main__":
    sys.exit(main())
