package com.repforth.core.model

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Locks the enums to what the pinned dataset actually contains.
 *
 * `dataset-vocabulary.json` is generated by `tools/extract-vocabulary.py` from
 * the dataset at the pinned commit and committed, so this runs without the 17 MB
 * download. When the pin moves, regenerating it turns any new upstream value
 * into a failing test — which is the point. The alternative is a value silently
 * becoming null at import time and an exercise quietly missing from every
 * filter that mentions its muscle.
 *
 * It also fails on *stale* constants, because an enum entry the dataset no
 * longer uses is dead weight that still shows up in a filter list.
 */
class CategoricalVocabularyTest {

    private val vocabulary: JsonObject by lazy {
        val stream = javaClass.classLoader!!.getResourceAsStream("dataset-vocabulary.json")
        requireNotNull(stream) {
            "dataset-vocabulary.json is missing. Run tools/extract-vocabulary.py."
        }.use { Json.parseToJsonElement(it.reader().readText()) as JsonObject }
    }

    private fun values(key: String): List<String> =
        vocabulary.getValue(key).jsonArray.map { it.jsonPrimitive.content }

    @Test
    fun `every body part in the dataset has a constant`() {
        assertEquals(values("bodyPart"), BodyPart.entries.map { it.slug }.sorted())
    }

    @Test
    fun `every equipment value in the dataset has a constant`() {
        assertEquals(values("equipment"), Equipment.entries.map { it.slug }.sorted())
    }

    @Test
    fun `every muscle in the dataset has a constant`() {
        assertEquals(values("muscle"), Muscle.entries.map { it.slug }.sorted())
    }

    @Test
    fun `the vocabulary was generated from the commit that is pinned now`() {
        // A vocabulary file left over from an older pin would let this whole
        // test class pass while describing a dataset the app no longer ships.
        val pin = Regex("""^commit *= *"([0-9a-f]{40})"""", RegexOption.MULTILINE)
            .find(java.io.File("../../dataset-version.toml").readText())
            ?.groupValues?.get(1)

        assertEquals(
            "dataset-vocabulary.json is stale. Re-run tools/extract-vocabulary.py.",
            pin,
            vocabulary.getValue("commit").jsonPrimitive.content,
        )
    }

    @Test
    fun `slug lookup round-trips for every constant`() {
        BodyPart.entries.forEach { assertEquals(it, BodyPart.fromSlug(it.slug)) }
        Equipment.entries.forEach { assertEquals(it, Equipment.fromSlug(it.slug)) }
        Muscle.entries.forEach { assertEquals(it, Muscle.fromSlug(it.slug)) }
    }

    @Test
    fun `synonyms collapse to a canonical muscle that is not itself a synonym`() {
        // Guards against a chain — mapping A to B while B maps to C would make
        // `canonical` depend on lookup order and quietly return a synonym.
        Muscle.entries.forEach { muscle ->
            val canonical = muscle.canonical
            assertEquals(
                "${muscle.slug} canonicalises to ${canonical.slug}, which is itself a synonym",
                canonical,
                canonical.canonical,
            )
        }
    }

    @Test
    fun `known synonym pairs resolve together`() {
        assertEquals(Muscle.ABS, Muscle.ABDOMINALS.canonical)
        assertEquals(Muscle.QUADS, Muscle.QUADRICEPS.canonical)
        assertEquals(Muscle.LATS, Muscle.LATISSIMUS_DORSI.canonical)
        assertEquals(Muscle.DELTS, Muscle.DELTOIDS.canonical)
        assertEquals(Muscle.PECTORALS, Muscle.CHEST.canonical)

        // And terms that are nested rather than synonymous stay distinct: these
        // are deliberate non-merges, not omissions.
        assertTrue(Muscle.LOWER_ABS.canonical != Muscle.ABS)
        assertTrue(Muscle.REAR_DELTOIDS.canonical != Muscle.DELTS)
        assertTrue(Muscle.SOLEUS.canonical != Muscle.CALVES)
    }

    @Test
    fun `the dataset attributes all media to a single holder`() {
        // §6 keeps media attribution intact in the UI. It is one constant string
        // across all 1,324 records, so it belongs in the manifest once rather
        // than on every row — this fails if that ever stops being true.
        assertEquals(1, values("attribution").size)
        assertTrue(values("attribution").single().contains("gymvisual.com"))
    }
}
